version: '3.8'

services:
    mysql-prod:
        image: mysql
        container_name: education-mysql-prod
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3407:3306
        environment:
            - MYSQL_ROOT_HOST=localhost
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=education_db
            - MYSQL_PASSWORD=education_password
            - MYSQL_DATABASE=education_prod
        networks:
            - education-network
        volumes:
            - /tmp/api-education-prod/mysql:/var/lib/mysql
    api-education-prod:
        platform: linux/amd64
        image: strider2598/strider:latest
        # build:
        #     context: ./api-service
        #     dockerfile: ./Dockerfile
        container_name: api-education-prod
        ports:
            - 10005:3000
        environment:
            - NODE_ENV=prod
        networks:
            - education-network
        depends_on:
            - mysql-prod
        volumes:
            - /tmp/api-education-prod/public/upload:/app/public/upload
networks:
    education-network:
volumes:
    education-prod:
        driver: local
