version: '3.8'

services:
    mysql:
        image: mysql
        container_name: education-mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3406:3306
        environment:
            - MYSQL_ROOT_HOST=localhost
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=education_db
            - MYSQL_PASSWORD=education_password
            - MYSQL_DATABASE=education_dev
        networks:
            - education-local-network
        volumes:
            - /tmp/education:/var/lib/mysql
networks:
    education-local-network:
volumes:
    education:
        driver: local