export const ROUTES = {
  USER: {
    HOME_PAGE: "/",
    REGISTER: "/register",
    LOGIN: "/login",
    SEARCH_RESULT: "/courses/search/:query",
    COURSES: "/courses/:category/:subcategory?/:topic?",
    FULL_COURSES: "/courses",
    TOPIC: "/topic/:topic?",
    TOPIC_PATH: "/topic/",
    TOPICS: "/topics",
    SUB_CATEGORIES: "/sub-categories",
    DETAIL_PRODUCT: "/detail/:uuid",
    DETAIL_PRODUCT_PATH: "/detail/",
    LIST_PRODUCT: "/list",
    CART: "/cart",
    EDIT_PROFILE: "/edit-profile",
    CHECK_OUT: "/checkout",
    LEARNING: "/learn",
  },
};
