let carouselProducts = [
  {
    id: 1,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Characters Design: AI Image Generation ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 4800000,
    level: "middle",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Creating Characters by Midjourney",
      "Techniques to Have Awsome Looks in Renders",
      "How to Use Midjourney Prompts",
    ],
    impression: [2],
  },
  {
    id: 2,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Character Designs: AI Image Generation ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 123213213,
    level: "beginnerLevel",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Creating Characters using Midjourney",
      "Techniques to Have Great Looks in Renders",
      "How to Use Midjourney Well",
    ],
    impression: [1, 2, 3],
  },
  {
    id: 3,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Character Design: AI Images Generation ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 123213213,
    level: "middle",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Creating Characters with Midjourney",
      "Techniques to Have Consistent Looks in Rendering",
      "How to Be Able To Use Midjourney Well",
    ],
    impression: [1],
  },
  {
    id: 4,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Character Design: AI Image Generations ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 123213213,
    level: "middle",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Creating Characters in Midjourney",
      "Techniques to Have Consistent Look in Rendering",
      "How Do We Use Midjourney",
    ],
    impression: [1],
  },
  {
    id: 5,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Character Design Propmts: AI Image Generation ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 123213213,
    level: "middle",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Creating Character using Midjourney",
      "Techniques to Get Consistent Looks in Renders",
      "How to Use Midjourney Effectively",
    ],
    impression: [1],
  },
  {
    id: 6,
    img: "https://img-c.udemycdn.com/course/240x135/5155816_30e6.jpg",
    title: "Midjourney Character Design: Good AI Image Generation ",
    author: "Jonathan Armandary",
    rate: 4.7,
    totalRate: 45,
    price: 230000,
    originalPrice: 450000,
    updateMoment: 1686557590578,
    totalTime: 123213213,
    level: "middle",
    subtitle: "subtitle",
    describe:
      "Create Consistent Characters for All Scenarios Using Midjourney AI ",
    mainContent: [
      "Create Characters using Midjourney",
      "Technique to Have Consistent Looks in Renders",
      "How to Use Midjourney?",
    ],
    impression: [1],
  },
];
export default carouselProducts;
