service:
  name: api-education
  title: Education API
  description: Swagger specification for API Education
  baseUrl: api/education
  docsBaseUrl: docs/education
  apiVersion: 0.1.0
  appVersion: 0.1.0

server:
  host: 127.0.0.1
  port: 3000
  hostname: 127.0.0.1:10005
  swaggerSchema: http

typeorm:
  type: mysql
  host: mysql-prod
  username: education_db
  password: education_password
  port: 3306
  database: education_prod
  entities: []
  logging: false